# Generated by Django 5.1.4 on 2025-01-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('average_temperature', models.FloatField()),
                ('carbon_emission', models.FloatField()),
            ],
        ),
    ]
