# Generated by Django 5.1.4 on 2025-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_educationalresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('country', 'Country'), ('organization', 'Organization'), ('individual', 'Individual')], max_length=15)),
                ('progress_percentage', models.PositiveIntegerField()),
                ('target', models.TextField()),
                ('source', models.URLField()),
            ],
        ),
    ]
