# Generated by Django 5.1.4 on 2025-01-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_climateaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateaction',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='climateaction',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
